name: NextJS check

on:
  pull_request:
    branches: [main]

jobs:
  check-next-website:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 7.1.0

      - uses: actions/checkout@v2

      - run: pnpm install

      - run: pnpm run lint

      - run: pnpm run build
