name: NextJS check

on:
  pull_request:
    branches: [main]

jobs:
  check-next-website:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js specified in the '.nvmrc' file
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Install node dependencies recursively
        uses: nick-fields/retry@v3
        with:
          command: pnpm i
          timeout_minutes: 15
          max_attempts: 3
          retry_on: error
      - name: Build 🔧
        run: |
          pnpm run lint
          pnpm run build
