name: NextJS check

on:
  pull_request:
    branches: [main]

jobs:
  check-next-website:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js specified in the '.nvmrc' file
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"

      - name: Install pnpm
        run: npm i -gf "pnpm@$(node -p 'require("./package.json").engines.pnpm')" && pnpm -v

      - run: pnpm install

      - run: pnpm run lint

      - run: pnpm run build
